/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/App` | `/App`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/DashboardScreen` | `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/DonationsScreen` | `/screens/DonationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/HomeScreen` | `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/InsightsScreen` | `/screens/InsightsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/LoginScreen` | `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/MarketplaceScreen` | `/screens/MarketplaceScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/TrackingInventoryScreen` | `/screens/TrackingInventoryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/App` | `/App`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screens/DashboardScreen` | `/screens/DashboardScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screens/DonationsScreen` | `/screens/DonationsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screens/HomeScreen` | `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screens/InsightsScreen` | `/screens/InsightsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screens/LoginScreen` | `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screens/MarketplaceScreen` | `/screens/MarketplaceScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/screens/TrackingInventoryScreen` | `/screens/TrackingInventoryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/App${`?${string}` | `#${string}` | ''}` | `/App${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screens/DashboardScreen${`?${string}` | `#${string}` | ''}` | `/screens/DashboardScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screens/DonationsScreen${`?${string}` | `#${string}` | ''}` | `/screens/DonationsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screens/InsightsScreen${`?${string}` | `#${string}` | ''}` | `/screens/InsightsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screens/MarketplaceScreen${`?${string}` | `#${string}` | ''}` | `/screens/MarketplaceScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/screens/TrackingInventoryScreen${`?${string}` | `#${string}` | ''}` | `/screens/TrackingInventoryScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/App` | `/App`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/DashboardScreen` | `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/DonationsScreen` | `/screens/DonationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/HomeScreen` | `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/InsightsScreen` | `/screens/InsightsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/LoginScreen` | `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/MarketplaceScreen` | `/screens/MarketplaceScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/screens/TrackingInventoryScreen` | `/screens/TrackingInventoryScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
